version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: securepassword
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  app:
    build: .
    container_name: sendme
    ports:
      - "8080:8000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
