name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user
          if [ -d "SendMe" ]; then
            cd SendMe
            git fetch origin
            git reset --hard origin/main
          else
            git clone https://github.com/whsiaor/SendMe.git             
            cd SendMe
          fi
          docker build -t sendme:latest .
          docker volume create mongodb_data || true  # 创建数据卷，如果已存在则忽略错误
          docker stop sendme || true
          docker rm sendme || true
          docker run -d --name sendme -v mongodb_data:/data/db --link mongodb:mongo -p 8080:8000 sendme:latest  # 映射数据卷并连接到 MongoDB 容器
